FROM golang:1.22 AS build

WORKDIR /src

COPY go.mod main.go ./

RUN CGO_ENABLED=0 go build -trimpath -ldflags="-s -w -buildid=" -o /out/app .

FROM scratch

COPY --from=build /out/app /app

ENTRYPOINT ["/app"]
